name: C/C++ CI

on:
  push:
    branches: [ "tyamauch-tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: norm check
      run: make norm
    - name: tests
      run: make test      
